AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  moontasirresturentmanagement


Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:


Outputs:

